version: 2

project_name: conf

builds:
  - binary: conf
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto

universal_binaries:
  - replace: true
    name_template: "{{ .ProjectName }}"

brews:
  - name: conf
    homepage: "https://confetti-cms.com"
    repo:
      owner: confetti-cms
      name: homebrew-conf
    commit_author:
      name: Reindert Vetter
      email: reindertvetter+brew@gmail.com

checksum:
  name_template: 'checksums.txt'
