# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Confetti < Formula
  desc ""
  homepage "https://confetti-cms.com"
  version "0.4.27"

  on_macos do
    url "https://github.com/confetti-cms/client/releases/download/0.4.27/client_0.4.27_darwin_all.tar.gz"
    sha256 "dbedafdaa626bea7de961e298a6033032d2e3056f198173e213e28a90ccb3f53"

    def install
      bin.install "client"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/confetti-cms/client/releases/download/0.4.27/client_0.4.27_linux_arm64.tar.gz"
      sha256 "f01891090a0e3eef44930e29b0caf03a31b87a3c65455442b2825b224b98e939"

      def install
        bin.install "confetti"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/confetti-cms/client/releases/download/0.4.27/client_0.4.27_linux_amd64.tar.gz"
      sha256 "eddf243da12bf2e63e913aeb9664497e484ddb2f2125c09dc5852ac152d897bf"

      def install
        bin.install "confetti"
      end
    end
  end
end
